In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("forestfires.csv")
df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [3]:
df = df.drop_duplicates()

In [4]:
df['log_area'] = np.log1p(df['area'])

In [5]:
df = df.drop(columns=['area'])

In [6]:
df = pd.get_dummies(df, columns=['month', 'day'], drop_first=True)

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numerical_cols = df.select_dtypes(include=np.number).columns

df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [8]:
df.head()
df.shape

(513, 28)

In [13]:
df.to_csv("/Users/sa25/Documents/Forest Fires/Forest-Fires/data/forestfires.csv", index=False)
          
print("File saved successfully")

File saved successfully

In [14]:
df.head()

,X,Y,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,month_may,month_nov,month_oct,month_sep,day_mon,day_sat,day_sun,day_thu,day_tue,day_wed
0,1.001657,0.569075,-0.801628,-1.322179,-1.837925,-0.858350,-1.835573,0.406971,1.498430,-0.073555,...,False,False,False,False,False,False,False,False,False,False
1,1.001657,-0.244116,-0.006761,-1.178717,0.484659,-0.508323,-0.152432,-0.694428,-1.733018,-0.073555,...,False,False,True,False,False,False,False,False,True,False
2,1.001657,-0.244116,-0.006761,-1.049290,0.556583,-0.508323,-0.736379,-0.694428,-1.510159,-0.073555,...,False,False,True,False,False,True,False,False,False,False
3,1.433101,1.382265,0.191956,-1.211464,-1.905808,-0.005160,-1.818399,3.221658,-0.005865,0.600261,...,False,False,False,False,False,False,False,False,False,False
4,1.433101,1.382265,-0.241608,-0.930777,-1.806003,0.126100,-1.285976,3.344035,-1.231586,-0.073555,...,False,False,False,False,False,False,True,False,False,False

In [15]:
print("Dataset shape:", df.shape)
print("Clean dataset saved.")

Dataset shape: (513, 28)
Clean dataset saved.